name: Test the ruby generator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruby-generator-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
      with:
        path: shared-slides
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.154.0
      with:
        working-directory: shared-slides
    - name: Check the Ruby syntax
      run: ruby -c shared-slides/preprocess.rb
    - uses: actions/checkout@v4.0.0
      with:
        repository: DanySK/Course-DTM-SE-3
        path: target
    - name: Run tests
      run: |
        shared-slides/preprocess.rb
        [ -s target/content/dvcs-basics/_index.md ]
  existing-websites-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - repo: DanySK/Course-DTM-SE-3
            folder: '.'
          - repo: unibo-spe/spe-slides
            folder: '.'
          - repo: DanySK/Course-Laboratory-of-Software-Systems
            folder: 'slides'
          - repo: apice-at-disi/oop-lab
            folder: 'slides-markdown'
    steps:
    - uses: actions/checkout@v4.0.0
      with:
        repository: ${{ matrix.target.repo }}
    - uses: actions/checkout@v4.0.0
      with:
        path: ${{ matrix.target.folder }}/shared-slides
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.154.0
      with:
        working-directory: ${{ matrix.target.folder }}/shared-slides
    - name: Run tests
      working-directory: ${{ matrix.target.folder }}
      run: |
        shared-slides/preprocess.rb
  generator-success:
    runs-on: ubuntu-latest
    needs:
      - ruby-generator-test
      - existing-websites-test
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
